# Generated by Django 3.1.1 on 2020-09-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='enter your first name here', max_length=20, null=True)),
                ('last_name', models.CharField(help_text='enter your surname here', max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
