# Generated by Django 3.1.1 on 2020-09-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('d', 'Delivered'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='d', max_length=1)),
            ],
        ),
    ]
