# Generated by Django 3.1.1 on 2020-09-08 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('d', 'Delivered'), ('O', 'Out for delivery'), ('P', 'Pending')], default='D', max_length=40, null=True),
        ),
    ]
