# Generated by Django 3.1.1 on 2020-09-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200909_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoors', 'Indoors'), ('Out', 'Out door')], max_length=7, null=True),
        ),
    ]
